### ISSUE TITLE
[BUG] Empty Subcategory in Edit Page is displayed incorrectly

### ISSUE THREAD

**Issue by clav1d** [rokwire/events-manager#1027]
**Describe the bug**
Empty Subcategory will be displayed as "Men's Basketball" in edit page.

**To Reproduce**
1. Create event with no subcategory
2. Click Edit after creating
3. See the bug

**Expected behavior**
It should be the same as Add New Event page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by bingzhang** [comment]
already fixed. close.

**Comment by sandeep-ps** [comment]
Fixed through https://github.com/rokwire/events-manager/issues/1039
