### ISSUE TITLE
[Feature] Add checkbox in dropdown menu.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1036]
https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/635c072bf964ca340b364a15
<img width="316" alt="Screen Shot 2023-01-31 at 10 03 19 AM" src="https://user-images.githubusercontent.com/5349154/215813709-e0bb176b-c483-4996-9b45-275c1221d45b.png">

**Comment by sandeep-ps** [comment]
This is not needed for the web app. I'll close this.
