### ISSUE TITLE
Add focus effect on buttons.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1049]
https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/635c072bf964ca340b364a15

**Comment by sandeep-ps** [comment]
Bing initially did the work in #1053, but later another feature, #1048, was merged first, and it had the necessary changes. Closing this issue as a duplicate.

**Comment by sandeep-ps** [comment]
Duplicate of https://github.com/rokwire/events-manager/issues/1048
