### ISSUE TITLE
Add disable effect on buttons.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1050]
https://app.zeplin.io/project/62b9dba49dd2b211410e608e/screen/635c072bf964ca340b364a15
https://user-images.githubusercontent.com/5349154/217023556-d1fd1e04-8eee-4074-bb62-ad803ef86d52.png

**Comment by sandeep-ps** [comment]
Bing initially did the work in #1052, but later another feature, #1048, was merged first and had the necessary changes. Closing this issue as a duplicate.

**Comment by sandeep-ps** [comment]
Duplicate of #1048.
