### ISSUE TITLE
[TASK] Add log to printout more details when failed to publish a user event.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#1113]
### Description

Need to print more information about the submission failure.

in publish_user_event function, log the status of error code and print out error content.
https://github.com/rokwire/events-manager/blob/develop/utilities/user_utilities.py#L335

### Acceptance Criteria
_Please describe what it means for this issue to be considered complete._

**Comment by minump** [comment]
Closing as done and merged.
