### ISSUE TITLE
[BUG] App won't display sub-events past 100 sub-events

### ISSUE THREAD

**Issue by vburgett** [rokwire/events-manager#1121]
The IlliniFest event now has over 100 sub-events. The sub-events at the end of the day on October 14 (presumably the sub-events over 100) are not showing up in the app. Is there a sub-event limit set? If yes, can it be increased to 150?

**Expected behavior**
I expect all sub-events of a super event to display in the app.

Illinois app v5.0.74 
@minump @sandeep-ps @bingzhang

**Comment by minump** [comment]
As per conversations in slack, issue connected to illinois app https://github.com/rokwire/illinois-app/issues/3790
