### ISSUE TITLE
[BUG] Events manager scheduler is not running at the specified time

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#134]
### Description
Currently, the Events Manager scheduler is running at about 1 pm daily, while it is set to run at 11 pm.

### Acceptance Criteria
The scheduler should run only at the time that is specified in the setting.

- [ ] user should be able to change the time in setting and save it

**Comment by bingzhang** [comment]
need to double check if it is time zone conversion.

**Comment by sandeep-ps** [comment]
This is currently not an issue.
