### ISSUE TITLE
[BUG] Page number is wrong.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#449]
### Description

click on the 5th page. The `...` appears wrong.

<img width="1154" alt="Screen Shot 2020-07-13 at 3 29 21 PM" src="https://user-images.githubusercontent.com/5349154/87350624-c2bb4e00-c51d-11ea-9b9d-09b8684ae009.png">

### Acceptance Criteria
Pagination works correctly.

**Comment by hjiang2** [comment]
![image](https://user-images.githubusercontent.com/32148302/104517613-f3a73900-55bb-11eb-8ac8-95e087187b08.png)
The bug of "12...34567....89" where there are dots between page 2 and page 3 is an internal bug inside the flask pagination page.

**Comment by sandeep-ps** [comment]
This is fixed.
