### ISSUE TITLE
Safari Issue: The Date/Time field just appears as a text box in the event form (Local+Deployed)

### ISSUE THREAD

**Issue by AnubhavG1999** [rokwire/events-manager#479]
**Describe the bug**
The date/time field on the form on MacOS just appears as a textbox with no formatting, probably a bootstrap incompatibility issue as suggested by @candicek 

**To Reproduce**
1. Open Safari and log onto events-manager
2. Click 'Create Event' or click on the event and select 'Edit Event'
3. In the Start and End date field, there should be no visible formatting
4. Date box just acts as a text box

**Expected behavior**
The start/end date field should have formatting to help the user enter their desired date and time

**Screenshots**
![Screen Shot 2020-07-28 at 2 21 35 PM](https://user-images.githubusercontent.com/32139698/88717846-c4bd0980-d0e6-11ea-8b66-e84ccaae8435.png)

**Desktop (please complete the following information):**
 - MacOS Catalina 10.15.5
 - Safari 

**Additional context**
Seems. to only be a Safari specific issue

**Comment by bingzhang** [comment]
@hjiang2 any update on it?
