### ISSUE TITLE
App cannot get the published user event

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#481]
**Describe the bug**
https://api-dev.rokwire.illinois.edu/manager-events/
publish the user event from api-dev. the event has been published to the events building. However, the dev version app cannot receive the events.

The newly published user event can be searched by the query from postman.

**To Reproduce**
1. Go to https://api-dev.rokwire.illinois.edu/manager-events/
2. Create a user event and publish it.
3. One app, search the title key words of this newly created user event.

**Expected behavior**
The app can receive the published user event.

**Smartphone (please complete the following information):**
 - Device: [e.g. Android]
 - Debug Version [1.2.45]

**Additional context**

**Comment by sandeep-ps** [comment]
Is this still an issue? I'm able to view the published event from the app Dev instance. If this is not an issue, we can close this. Thanks.

**Comment by bingzhang** [comment]
close.
