### ISSUE TITLE
[TASK] Filter unnecessary fields before uploading

### ISSUE THREAD

**Issue by clav1d** [rokwire/events-manager#490]
### Description
Some fields (e.g.: 'name' in the sub-event list in the super event) that are not in the schema in the event document should be removed before uploading to the building block.

### Acceptance Criteria
These unnecessary fields are removed before uploading.

**Comment by bingzhang** [comment]
@clav1d I think this is done. please confirm. then we can close it.

**Comment by clav1d** [comment]
> @clav1d I think this is done. please confirm. then we can close it.

I checked and there still some fields didn't get deleted before uploading to the building block like "name" in the sub-events array,
![image](https://user-images.githubusercontent.com/8536258/97501841-ffca1580-193f-11eb-83ee-cc4aa8bd9ffd.png)
 I will check it throughout and fix it this week.
