### ISSUE TITLE
[FEATURE] Process `virtualEvent` flag coming from WebTools

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#526]
**Is your feature request related to a problem? Please describe.**
A new boolean flag called has been added to WebTools calendar XML data. We need to use that to set the isVirtual flag for events in the Events Manager and Events Building Block. This is in version 13 of WebTools calendar API.
Schema: https://xml.calendars.illinois.edu/calendarws13.xsd.
Example event: https://xml.calendars.illinois.edu/eventXML13/7.xml?startDate=07%2F01%2F2020&endDate=07%2F23%2F2020    
Both these URLs are accessible from the VPN.

**Describe the solution you'd like**
1. If in a WebTool calendar event, `virtualEvent` flag is set to `true`, in the Events Manager's local database, `isVirtual` flag should be set to `true` for this particular event, and this data should be sent to Events Building Block during daily push. 
2. `isVirtual` flag needs to be set for existing events as well. 
3. Rokwire event's `isVirtual` flag should then  be used to ignore geolocation calculation along with some keywords that are currently being used to perform the same.
4. `isVirtual` flag name and value should also be displayed in the source calendar detail view in Events Manager.

**Describe alternatives you've considered**
No other alternatives were considered at this time.

**Additional context**

**Comment by bingzhang** [comment]
done.close.
