### ISSUE TITLE
[FEATURE] Let user to choose the number of events per page.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#586]
on the events page, make a dropdown menu to let user to choose how many events to show per page.

e.g., allow “view all” or “view 20, 50, 100”

**Comment by hjiang2** [comment]
Filter to show or hide events that have passed (or add a date range selector) 
In grid display, allow “view all” or “view 20, 50, 100” to avoid paging In grid display, show the flag to indicate which are super events.
 In grid display, show start date of the event and always show latest date at the top

**Comment by bingzhang** [comment]
@hjiang2 any update on this?
