### ISSUE TITLE
[FEATURE] Filter to show events within a time range

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#588]
on event page, let users to enter the startdate and enddate to specify the time range search. All satisfied events will be shown on the page.

@clav1d you can start work on the backend function to query events based on the user input, e.g., startdate, enddate.

**Comment by clav1d** [comment]
The backend functions are added to https://github.com/rokwire/events-manager/blob/event-time-range/utilities/user_utilities.py

**Comment by bingzhang** [comment]
@hjiang2 any update on the frontend GUI?

**Comment by bingzhang** [comment]
@clav1d is there pr of your code?

**Comment by clav1d** [comment]
> @clav1d is there pr of your code?

Not yet, but I pushed the code to this branch: https://github.com/rokwire/events-manager/blob/event-time-range/utilities/user_utilities.py

**Comment by bingzhang** [comment]
@clav1d ok, can you also work on the GUI, and make a pr of it?

**Comment by clav1d** [comment]
> @clav1d ok, can you also work on the GUI, and make a pr of it?

OK.
