### ISSUE TITLE
[TASK] AWS DEV instance needs to be setup with static IP addresses

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#598]
### Description
api-dev cannot download campus events. It is because that the AWS DEV instance needs to be setup with static IP addresses.

### Acceptance Criteria
set to static IP address of events manager and events manager can download campus events.

**Comment by sandeep-ps** [comment]
This is complete and can be closed.

**Comment by sandeep-ps** [comment]
Closing.
