### ISSUE TITLE
[EPIC] Select existing tags when creating/editing an event

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#608]
### Description
As a regular user, I need to select one or more existing tags from the Events Building Block using an autocomplete textbox and add those to an event when creating/editing it to use the same set of tags in Events Manager and Illinois app. 

As a regular user, I should not be able to add new tags when creating/editing events.

### Aceptance Criteria
Users can select existing tags from the Events Building block using an autocomplete feature and not create new ones.

**Comment by bingzhang** [comment]
this should be done. @sandeep-ps

**Comment by sandeep-ps** [comment]
Closing.
