### ISSUE TITLE
[FEATURE] Add checkbox to indicate an event is free.

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#635]
**Is your feature request related to a problem? Please describe.**
WebTools recently added a boolean field to indicate if an event is free. We need to add a similar checkbox to User Events.

**Describe the solution you'd like**
Please add a check box called `Free Event` to the new/edit event user interface. If selected, this will set a database entry called `isEventFree` to `true`. This data item should be sent to Events Buiding Block when creating/updating an event. Please update the UI label `Cost` to `Cost Description`.

**Describe alternatives you've considered**

**Additional context**
Epic: #639

**Comment by sandeep-ps** [comment]
@clav1d, Could you please create a follow-up issue to move the "Free Event" label and checkbox above the Cost Description section? I think that may be a more logical position for that control. Thanks.

CC: @bingzhang

**Comment by clav1d** [comment]
> @clav1d, Could you please create a follow-up issue to move the "Free Event" label and checkbox above the Cost Description section? I think that may be a more logical position for that control. Thanks.
> 
> 
> 
> CC: @bingzhang 

Will do.
