### ISSUE TITLE
[EPIC] Events Manager to use Groups Building Block for User Events Authorization

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#638]
### Description
As a developer, I need to use Groups Building Block to handle authorization for User Events in Events Manager. Following features will be needed to meet the goals of this Epic:

1. A user should be granted access to Events Manager User Events space only if they are a member of the Rokwire Group Access AD group `urn:mace:uiuc.edu:urbana:authman:app-rokwire-service-policy-rokwire groups access` (this AD group membership is verified by the Events Building Block when creating an Event) and is an admin member in at least one of Rokwire Groups (obtained from the Groups Building Block).
2. After the user successfully logs in, Events Manager needs to get a list of all Rokwire Groups in which the user is an admin and then provide Read/Write access to all user events created by those Groups. A user can view only those events they can manage because of being an admin member in one or more Rokwire Groups. All other events will not be accessible/viewable by the user.
3. When creating a new event, the user needs to select one of the Groups it will belong to. The Group's ID  will need to be stored in the `createdByGroupId` field in the Event Schema. The Events Manager will later use this information to provide access to all admin users of this Group.
4. A user can change the Rokwire Group the event belongs to using the edit option.

### Acceptance Criteria
Events Manager uses Groups Building Block for authorizing access to User Events.

**Comment by AnubhavG1999** [comment]
1, 2 & 3 are done here.

**Comment by sandeep-ps** [comment]
This is complete. Thanks.
