### ISSUE TITLE
[EPIC] Update User Event create/edit/view pages

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#639]
### Description
As a developer, I need to update the User Event edit/create page to improve the user experience and to gather more data. 

Relevant features:

1. Update Event URL field
2. Show a URL field for virtual events
3. Add checkbox to indicate an event is free.
4. Add fields to store event registration details

### Acceptance Criteria
All the relevant features are complete.

**Comment by bingzhang** [comment]
it should be close.

**Comment by sandeep-ps** [comment]
Thanks. Closing this EPIC as relevant tasks are complete.
