### ISSUE TITLE
[EPIC] Update User Events space

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#641]
### Description
As a developer, I need to update the User Events space for a better user experience.

Relevant features:

1. Reduce font size to show more content
2. Update date format to MM-DD-YYYY HH:MM AM/PM
3. Crop event title at a fixed number of characters. The complete title can continue to be displayed in the event detail view.
4. Move dates under a second row below the title. Move badges to the right of the title.
5. Firefox and Safari do not support input datetime-local control (https://www.w3schools.com/tags/att_input_type_datetime-local.asp). Either we need to find a better datetime selector or split datetime into date and time selectors.
6. Move the `Create Event` button to the title bar
7. Move `Events per page` to the right of the `Reset` button
8. Change `Hide Past Event` to `Hide Past Events`
9. In the event listing, if "End date" is missing, let's not don’t show the label and `Not Available`.

### Acceptance Criteria
User Events space user interface updated.

**Comment by bingzhang** [comment]
@clav1d will work on the 1, 2, 6,7.

**Comment by bingzhang** [comment]
@clav1d  will continue to work on the 3,4, 5.

**Comment by bingzhang** [comment]
@AnubhavG1999 will work on tasks 8,9.

**Comment by sandeep-ps** [comment]
@bingzhang and @clav1d, I think we can proceed with task 4 on this list. If there is any other change related to this, we can make them later.

**Comment by sandeep-ps** [comment]
This EPIC has open features. Re-opening.

**Comment by AnubhavG1999** [comment]
With the not available tag removed, is everything on this epic completed?

**Comment by sandeep-ps** [comment]
Yes, this Epic looks complete. Closing. Thanks.
