### ISSUE TITLE
[FEATURE] Reduce font size to show more content on user event browse page.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#654]
#641

**Comment by sandeep-ps** [comment]
![image](https://user-images.githubusercontent.com/4306604/122094965-623e2c00-cdd2-11eb-948f-62b29bdbde10.png)
Please reduce the font sizes of the event title and date label from h4 to h5 and h5 to h6 respectively, and the font size of the date string to `small`. Please use CSS classes. 

It looks like there is also a lot of padding space in the cell. Please see if there is a standard/better way to reduce the overall vertical dimension of a row using Bootstrap.
