### ISSUE TITLE
[BUG] Current backend logic for showing date on event list is not compatible with all-day event

### ISSUE THREAD

**Issue by clav1d** [rokwire/events-manager#662]
### Description
Back end logic will break when there is an all-day event on the list

### Acceptance Criteria
Backend code is compatible with an all-day event

**Comment by bingzhang** [comment]
@clav1d do a try catch the exception and convert the all day event datatime.

**Comment by sandeep-ps** [comment]
This is an example of the start date (06/23/2021 06:00:00) and end date (06/24/2021 05:59:00) for an all-day event. I am not talking about the format, but the value in the database in UTC should be similar. In the Central timezone, this will be an all-day event happening today (06/23/2021).

**Comment by clav1d** [comment]
Fixed by #669 and #665
