### ISSUE TITLE
[BUG] PER_PAGE needs to be evaluated correctly

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#670]
**Describe the bug**
PER_PAGE in config.template.py needs to be evaluated correctly.

**To Reproduce**
1. Set PER_PAGE environment variable.
2. Run Events Manager
3. See error when clicking on User Events and visiting calendar.

**Expected behavior**
The Events Manager should run properly.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser: Chrome
 - Version: 2.4.1

**Additional context**

**Comment by clav1d** [comment]
This will be fixed by #719
