### ISSUE TITLE
[FEATURE] show group name on the user event create/edit pages.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#674]
with the given a list of group information ( e.g., group id, group name), write a function to get the group name for this event (given event id) and add a new GUI field to show this group name on the event create/edit pages. Display only those groups that the user is an admin of. When a user selects this group, its group ID needs to be added to the `createdByGroupId` field in the event. `isGroupPrivate` can be set to `false` for now.

#638

**Comment by sandeep-ps** [comment]
Example list of groups: 
```
[
{
        "id": "3a931ffb-d928-11eb-9c02-0286d10e0848",
        "title": "Generic Soft Car",
        "privacy": "private",
        "membership_status": "admin"
    },
    {
        "id": "45069a52-d928-11eb-9c02-0286d10e0848",
        "title": "Fantastic Soft Chair",
        "privacy": "public",
        "membership_status": "admin"
    }
]
```
