### ISSUE TITLE
[BUG] Free event will not publish the first time

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/events-manager#697]
**Describe the bug**
I get an error when trying to publish an event with the Free checkbox marked.

**To Reproduce**
1. Go to events manager, user events, and then click on Create Event
2. Enter a title, category, time zone, start date and end date
3. Check the Free Event checkbox and then click Add button at the bottom
4. The event is shown in pending. Notice the Free Event field says Yes
5. Click on Publish and see an error "failed on events approval"
6. Click on Edit. The Free Event checkbox is empty, even though the last screen said it was on, and we checked it the first time we saved the event.
7. Check the Free Event box again, the click Save
8. Now click on Publish and it succeeds.

**Expected behavior**
The event should publish on the first attempt.
The Free Event checkbox should be checked when we go back to edit the event.

**Screenshots**
Here is a video recording of the issue:
https://uofi.box.com/s/r4xfeebl4jqcodbs625m7nf6ddj9nznj

**Comment by sandeep-ps** [comment]
@isaac-galvan, this has been fixed in code. After @bingzhang deploys the latest code to the DEV instance, you should be able to review the fix. I will let you know when it's ready. Thanks.
