### ISSUE TITLE
[BUG] Unexpected error when showing Pending events

### ISSUE THREAD

**Issue by isaac-galvan** [rokwire/events-manager#704]
**Describe the bug**
I get an error when trying to view Pending events.

**To Reproduce**
1. Go to User Events in Events Manager. Published events are checked by default
2. Click on Pending to also show events pending.
3. Uncheck Published and the screen updates to show "Unexpected error, please try again."

**Expected behavior**
The pending events are shown

**Screenshots**
<img width="1131" alt="Screen Shot 2021-08-04 at 5 19 26 PM" src="https://user-images.githubusercontent.com/11352701/128262699-88c19733-5861-4811-a70e-f8addc300316.png">

**Desktop (please complete the following information):**
 - OS: Mac OS 11.5.1
 - Browser Chrome and Vivaldi

**Comment by sandeep-ps** [comment]
@isaac-galvan, this should be fixed now. Please check the latest DEV instance (https://api-dev.rokwire.illinois.edu/manager-events/). We also have included Groups authorization feature and a few other improvements and bug fixes there.

**Comment by sandeep-ps** [comment]
Closing this as it's fixed.
