### ISSUE TITLE
[FEATURE] script to add group id by the given list of event id and group id.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#739]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by sandeep-ps** [comment]
Just to add a little more detail, this script needs to add `"createdByGroupId": "<group_Id>"` and  `"isGroupPrivate": false` to each event based on event_id - group_Id mapping in a CSV file.
