### ISSUE TITLE
[HOTFIX] Fix login to use Groups Building Block

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#755]
**Describe the bug**
Currently, the initial login logic is not using Groups Building Block to grant access to User Events Space. Hence, those users who are admins of at least one Rokwire Group are not able to log in. 

**To Reproduce**
1. Make sure that you are not part of the `rokwire em user events admins` AD group.
2. Click the login button.
3. See access error.

**Expected behavior**
Those users who are admin of at least one Rokwire Group should be able to log in to User Events Space. Only those users should be able to log in to User Events Space.

**Desktop (please complete the following information):**
 - Version 3.0.2

**Comment by bingzhang** [comment]
close
