### ISSUE TITLE
[BUG] Subevent linked to only one superevent

### ISSUE THREAD

**Issue by minump** [rokwire/events-manager#801]
**Describe the bug**
Subevent stores only one superEventId. If the same event is a subevent for multiple super events, the latest superEventId is over-written to the field.

**To Reproduce**
1. Create an event (Eg: subeventA)
2. Create 2 superevents (Eg: supereventAA and supereventAAA)
3. Link subevent to both superevents
4. Only the latest link is reflected in the superEventId field of the subevent.

**Expected behavior**
Subevent can be a part of multiple super events. Change the superEventId field to an array instead of string.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sandeep-ps** [comment]
I'm also closing this issue as this issue. Thanks.

Ref: https://github.com/rokwire/events-manager/pull/802#issuecomment-1075529353
