### ISSUE TITLE
[FEATURE] Add navigation back to super event from sub event.

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#853]
**Is your feature request related to a problem? Please describe.**
Currently, we don't have navigation from sub-event to super event.

**Describe the solution you'd like**
Please add a button called "Back To Super Event" to the right of "Back To All Events" to navigate from a sub-event to its super event.

<img width="849" alt="image" src="https://user-images.githubusercontent.com/4306604/161846868-ef06baa8-6a9f-4a3b-9b5f-633087b2c542.png">

**Describe alternatives you've considered**
An alternative will be to use a combination of icons and text. E.g., https://icons.getbootstrap.com/icons/back/. Sharing the link here for future reference.

**Additional context**
The position and appearance of this button or link may eventually change. This is just to have basic navigation in place.

**Comment by sandeep-ps** [comment]
@bingzhang, Could you please work on this feature in the current sprint?

**Comment by bingzhang** [comment]
Sure. But I think it should be a hyper link to the super event?

**Comment by sandeep-ps** [comment]
Thanks. Yes, it can just be a hyperlink too.

**Comment by bingzhang** [comment]
> Thanks. Yes, it can just be a hyperlink too.

After meeting, we will implement it as a button.
