### ISSUE TITLE
[FEATURE] Change “Switch Space” button to “Home”, move to the left side of the menu bar (to the right of Events Manager link), and change link to "/" (e.g., https://api.rokwire.illinois.edu/manager-events/)

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#868]

**Comment by bingzhang** [comment]
@sandeep-ps I thought there is no switch space, right? that page is obsolete.

**Comment by bingzhang** [comment]
> @sandeep-ps I thought there is no switch space, right? that page is obsolete.

ok never mind. it is on user or campus event page.
