### ISSUE TITLE
[BUG] User event failed to check required fields.

### ISSUE THREAD

**Issue by bingzhang** [rokwire/events-manager#893]
on user event create/edit page, leave required fileds, and do add or save the changes.
The page should stay and remind users to fill in the required fields.

**Comment by sandeep-ps** [comment]
Hi, @clav1d, I'm assigning this to you as Bing is away. Please let me know if you have any questions. I think we need to release the next version once this bug is fixed. Thanks.

**Comment by clav1d** [comment]
> Hi, @clav1d, I'm assigning this to you as Bing is away. Please let me know if you have any questions. I think we need to release the next version once this bug is fixed. Thanks.

OK, I'll look into this ASAP.
