### ISSUE TITLE
[BUG] H1 styles appearing in the deployed DEV instance don't match the design

### ISSUE THREAD

**Issue by sandeep-ps** [rokwire/events-manager#982]
From Events Manager DEV: 
<img width="226" alt="image" src="https://user-images.githubusercontent.com/4306604/199082823-bf4ebe63-4357-4f59-89e3-5f98dd0ca89f.png">

From Zeplin: 
<img width="192" alt="image" src="https://user-images.githubusercontent.com/4306604/199082915-f817d58f-cb14-45be-b1dc-5b7000d0df5f.png">

Please see the difference. This might be a result of other default styles interfering. I'm creating this issue for fixing later. This shouldn't affect the release. Thanks.

**Comment by bingzhang** [comment]
there is a pr in progress to change the font size of h1, h2, etc.
https://github.com/rokwire/events-manager/pull/976

**Comment by sandeep-ps** [comment]
Oh! That's right. Then I will close this as a duplicate.
